config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :blog_entries
  end

  scope Spree::Config['blog_alias'], as: 'blog' do
    get '/tag/:tag' => 'blog_entries#tag', :as => :tag
    get '/category/:category' => 'blog_entries#category', :as => :category
    get '/author/:author' => 'blog_entries#author', :as => :author
    get '/:year/:month/:day/:slug' => 'blog_entries#show', :as => :entry_permalink
    get '/:year(/:month)(/:day)' => 'blog_entries#archive', :as => :archive, 
      :constraints => {:year => /(19|20)\d{2}/, :month => /[01]?\d/, :day => /[0-3]?\d/}
    get '/feed' => 'blog_entries#feed', :as => :feed, :format => :rss
    get '/' => 'blog_entries#index'
  end
end

app/models/spree/app_configuration_decorator.rb
Spree::AppConfiguration.class_eval do
  preference :blog_alias, :string, default: 'blog'
end

app/models/spree/blog_entry.rb
require 'acts-as-taggable-on'

class Spree::BlogEntry < ActiveRecord::Base
  acts_as_taggable_on :tags, :categories
  before_save :create_permalink
  before_save :set_published_at
  validates_presence_of :title
  validates_presence_of :body

  default_scope { order("published_at DESC") }
  scope :visible, -> { where :visible => true }
  scope :recent, lambda{|max=5| visible.limit(max) }

  if Spree.user_class
    belongs_to :author, :class_name => Spree.user_class.to_s
  else
    belongs_to :author
  end

  has_one :blog_entry_image, :as => :viewable, :dependent => :destroy, :class_name => 'Spree::BlogEntryImage'
  accepts_nested_attributes_for :blog_entry_image, :reject_if => :all_blank

  def entry_summary(chars=200)
    if summary.blank?
      "#{body[0...chars]}..."
    else
      summary
    end
  end

  def self.by_date(date, period = nil)
    if date.is_a?(Hash)
      keys = [:day, :month, :year].select {|key| date.include?(key) }
      period = keys.first.to_s
      date = DateTime.new(*keys.reverse.map {|key| date[key].to_i })
    end

    time = date.to_time.in_time_zone
    where(:published_at => (time.send("beginning_of_#{period}")..time.send("end_of_#{period}")) )
  end

  def self.by_tag(tag_name)
    tagged_with(tag_name, :on => :tags)
  end

  def self.by_category(category_name)
    tagged_with(category_name, :on => :categories)
  end

  def self.by_author(author)
    where(:author_id => author)
  end

  # data for news archive widget, only visible entries
  def self.organize_blog_entries
    Hash.new.tap do |entries|
      years.each do |year|
        months_for(year).each do |month|
          date = DateTime.new(year, month)
          entries[year] ||= []
          entries[year] << [date.strftime("%B"), self.visible.by_date(date, :month)]
        end
      end
    end
  end

  private

  def self.years
    visible.map {|e| e.published_at.year }.uniq
  end

  def self.months_for(year)
    visible.select {|e| e.published_at.year == year }.map {|e| e.published_at.month }.uniq
  end

  def create_permalink
    self.permalink = title.to_url if permalink.blank?
  end

  def set_published_at
    self.published_at = Time.now if published_at.blank?
  end

  def validate
    # nicEdit field contains "<br>" when blank
    errors.add(:body, "can't be blank") if body =~ /^<br>$/
  end

end

app/models/spree/blog_entry_image.rb
class Spree::BlogEntryImage < Spree::Image
  has_attached_file :attachment, 
     :styles => {
        
         pico:     "16x16>",
         icon:     "32x32>",
         mini:     "48x48>",
         thumb:    "50x50>",
         small:    "100x100>",
         compact:  "160x160>",
         medium:   "240x240>",
         product:  "240x240>",
         large:    "480x480>",
         grande:   "600x600>",
         super: "1024x1024>",
         extra: "2048x2048>",
     },
     :s3_credentials => {
          access_key_id: ENV['AWS_ACCESS_KEY_ID'],
          secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
          bucket: ENV['S3_BUCKET_NAME']
        },
        :default_style => :large,
        :s3_host_alias => 'cdn.tokyowheel.com',
        :storage=> :s3,
        :s3_headers =>     { "Cache-Control" => "max-age=31557600" },
        :s3_protocol =>    "http",
        :bucket =>         ENV["S3_BUCKET"],
        path:           "/files/:id/:basename_:style.:extension",
        url:            ":s3_alias_url",
        default_url:    "/files/:id/:basename_:style.:extension"
end

app/models/spree/user_decorator.rb
if Spree.user_class
  Spree.user_class.class_eval do
    has_many :blog_entries, :foreign_key => :author_id
  end
end

Spree::PermittedAttributes.user_attributes.push :nickname, :website_url, :google_plus_url, :bio_info

app/controllers/spree/admin/blog_entries_controller.rb
class Spree::Admin::BlogEntriesController < Spree::Admin::ResourceController
  helper 'spree/blog_entries'


  private

    def location_after_save
      edit_admin_blog_entry_url(@blog_entry)
    end

    def collection
      page = params[:page].to_i > 0 ? params[:page].to_i : 1
      per_page = params[:per_page].to_i > 0 ? params[:per_page].to_i : 20
      model_class.page(page).per(per_page)
    end

end

app/controllers/spree/blog_entries_controller.rb
class Spree::BlogEntriesController < Spree::StoreController
  helper 'spree/blog_entries'

  before_action :init_pagination, :only => [:index, :tag, :archive, :author, :category]
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404

  def index
    @blog_entries = Spree::BlogEntry.visible.page(@pagination_page).per(@pagination_per_page)
  end

  def show
    if try_spree_current_user.try(:has_spree_role?, "admin")
      @blog_entry = Spree::BlogEntry.find_by_permalink!(params[:slug])
    else
      @blog_entry = Spree::BlogEntry.visible.find_by_permalink!(params[:slug])
    end
    @title = @blog_entry.title
  end

  def tag
    @blog_entries = Spree::BlogEntry.visible.by_tag(params[:tag]).page(@pagination_page).per(@pagination_per_page)
    @tag_name = params[:tag]
  end

  def category
    @blog_entries = Spree::BlogEntry.visible.by_category(params[:category]).page(@pagination_page).per(@pagination_per_page)
    @category_name = params[:category]
  end

  def archive
    @blog_entries = Spree::BlogEntry.visible.by_date(params).page(@pagination_page).per(@pagination_per_page)
  end

  def feed
    @blog_entries = Spree::BlogEntry.visible.limit(20)
    render :layout => false
  end

  def author
    @author = Spree.user_class.where(:nickname => params[:author]).first
    @blog_entries = Spree::BlogEntry.visible.by_author(@author).page(@pagination_page).per(@pagination_per_page)
  end

  private

    def init_pagination
      @pagination_page = params[:page].to_i > 0 ? params[:page].to_i : 1
      @pagination_per_page = params[:per_page].to_i > 0 ? params[:per_page].to_i : 10
    end
end

app/controllers/spree/store_controller_decorator.rb
Spree::StoreController.class_eval do 
  helper 'spree/blog_entries'
end

app/helpers/spree/admin/navigation_helper_decorator.rb
Spree::Admin::NavigationHelper.class_eval do
  def link_to_blog_in_store(resource, options={})
    url = options[:url] || blog_entry_permalink(resource)
    #options[:data] = {:action => 'show'}
    link_to(Spree.t(:view_in_store), url, options)
  end
end

app/helpers/spree/blog_entries_helper.rb
module Spree
  module BlogEntriesHelper
    def post_link_list
     link = Struct.new(:name,:url)
     BlogEntry.recent.collect { |post| link.new( post.title, blog_entry_permalink(post)) }
    end

    def blog_entry_permalink(e)
      unless e.published_at.nil?
        blog_entry_permalink_path :year => e.published_at.strftime("%Y"), :month => e.published_at.strftime("%m"), :day => e.published_at.strftime("%d"), :slug => e.permalink
      else
        blog_entry_permalink_path :year => "na", :month => "na", :day => "na", :slug => e.permalink
      end
    end

    def blog_entry_url_permalink(e)
      unless e.published_at.nil?
         blog_entry_permalink_url :year => e.published_at.strftime("%Y"), :month => e.published_at.strftime("%m"), :day => e.published_at.strftime("%d"), :slug => e.permalink
       else
        blog_entry_permalink_url :year => "na", :month => "na", :day => "na", :slug => e.permalink
      end
    end

    def blog_full_article_html(blog_entry)
      "<br><br>Read the full article #{link_to blog_entry.title, blog_entry_url_permalink(blog_entry)} at #{link_to "#{Spree::Store.current.name} Blog", blog_url}."
    end

    def blog_first_appeared_html(blog_entry)
      "<br><br>The article #{link_to blog_entry.title, blog_entry_url_permalink(blog_entry)} first appeared on #{link_to "#{Spree::Store.current.name} Blog", blog_url}."
    end

    def blog_entry_tag_list_html blog_entry
      blog_entry.tag_list.map {|tag| link_to tag, blog_tag_path(tag) }.join(", ").html_safe
    end

    def blog_entry_category_list_html blog_entry
      blog_entry.category_list.map {|category| link_to category, blog_category_path(category) }.join(", ").html_safe
    end

    def tag_cloud(tags, classes)
      return [] if tags.blank?
      max_count = tags.sort_by(&:count).last.count.to_f
      tags.each do |tag|
        index = ((tag.count / max_count) * (classes.size - 1))
        yield tag, classes[index.nan? ? 0 : index.round]
      end
    end
  end
end

app/views/spree/blog_entries/_blog_entries.html.erb
<div id="blog_entry_container" class="">
  <% if !@blog_entries.empty? %>
    <ul id="blog_entry_entries">
      <% @blog_entries.each do |blog_entry| %>
        <li>
          <%= render :partial => 'spree/blog_entries/blog_entry', :locals => {:blog_entry => blog_entry} %>
        </li>
      <% end %>
    </ul>
    <%= paginate @blog_entries %>
  <% else %>
    <p id="no_entries"><%= Spree.t(:no_blog_entries) %></p>
  <% end %>
</div>

app/views/spree/blog_entries/_blog_entry.html.erb
<h2><%= link_to blog_entry.title, blog_entry_permalink(blog_entry) %></h2>

<div class="blog_entry_summary">
  <%== blog_entry.entry_summary %>
  <span class="blog_read_more"><%= link_to Spree.t(:blog_read_more), blog_entry_permalink(blog_entry) %></span>
</div>

<%= render :partial => 'spree/blog_entries/blog_entry_details', :locals => {:blog_entry => blog_entry} %>

app/views/spree/blog_entries/_blog_entry_details.html.erb
<div class="blog_entry_details">
  <%= Spree.t(:posted_on) %> <span class="blog_entry_date"><%= l(blog_entry.published_at, :format => :blog_date) %></span>
  <% unless blog_entry.author.blank? or blog_entry.author.nickname.blank? %>
    <%= Spree.t(:by) %> <%= link_to blog_entry.author.nickname, blog_author_path(:author => blog_entry.author.nickname), class: "blog_entry_author" %>
  <% end %>.
  <% unless blog_entry.category_list.empty? %>
    <%= Spree.t(:posted_in) %> <%= blog_entry_category_list_html blog_entry %>.
  <% end %>
  <% unless blog_entry.tag_list.empty? %>
    <%= Spree.t(:tagged) %> <%= blog_entry_tag_list_html blog_entry %>.
  <% end %>
</div>

app/views/spree/blog_entries/_blog_sidebar.html.erb
<div id="blog_entry_sidebar">
  <%= render 'spree/blog_entries/categories_list' %>
  <%= render 'spree/blog_entries/tag_cloud' %>
  <%= render 'spree/blog_entries/recent_blog_entries', recent_blog_entries: Spree::BlogEntry.recent(10) %>
  <%= render 'spree/blog_entries/news_archive', news_archive: Spree::BlogEntry.organize_blog_entries %>
</div>

app/views/spree/blog_entries/_categories_list.html.erb
<% categories = Spree::BlogEntry.visible.tag_counts_on(:categories).sort_by(&:count) %>
<% if categories.present? %>
  <div class="blog_categories_list_wrapper">
    <h6><%= Spree.t('blog.categories') %></h6>
    <ul class="blog_categories_list">
      <% categories.reverse.each do |category| %>
        <li><%= link_to category.name, blog_category_path(category.name) %> (<%= category.count %>)</li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/spree/blog_entries/_comments.html.erb
<div id="blog_entry_comments">
</div>

app/views/spree/blog_entries/_news_archive.html.erb
<div class="blog_news_archve_wrapper">
  <h6><%= Spree.t('blog.archive') %></h6>
  <ul id="news-archive">
    <% news_archive.to_a.reverse.each do |year, months_with_entries| %>
      <% d = DateTime.parse("1/#{year}") %>

      <li> <span></span>
        <%= link_to(year, blog_archive_path(:year => d.year)) %>

        <ul class="months">
          <% months_with_entries.each do |month, entries| %>
            <% d = DateTime.parse("#{year}, #{month}") %>

            <li> <span></span>
              <%= link_to I18n.l(d, :format => "%B"), blog_archive_path(:year => d.year, :month => d.month) %>

              <ul class="posts">
                <% entries.each do |entry| %>
                  <li><%= link_to(entry.title, blog_entry_permalink(entry)) %></li>
                <% end %>
              </ul>
            </li>

          <% end %>
        </ul>
      </li>
    <% end %>
  </ul>
</div>

app/views/spree/blog_entries/_recent_blog_entries.html.erb
<% if recent_blog_entries.present? %>
  <div class="recent_blog_entries_wrapper">
    <h6><%= Spree.t('blog.recent_entries') %></h6>
    <ul class="recent_blog_entries">
      <% recent_blog_entries.each do |blog_entry| %>
        <li>
          <%= link_to(blog_entry_permalink(blog_entry)) do %>
            <%= blog_entry.title %>
            <span class="blog_entry_date"><%= "#{time_ago_in_words blog_entry.published_at} #{Spree.t('blog.ago')}" %></span> 
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/spree/blog_entries/_tag_cloud.html.erb
<div class="blog_tag_cloud_wrapper">
  <h6><%= Spree.t('blog.tags') %></h6>
  <ul class="blog_tag_cloud">
    <% tags = Spree::BlogEntry.visible.tag_counts_on(:tags) %>
    <% tag_cloud(tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
      <li>
        <%= link_to tag.name, blog_tag_path(tag.name), :class => css_class %>
      </li>
    <% end %>
  </ul>
</div>

app/views/spree/blog_entries/archive.html.erb
<% content_for :sidebar do %>
  <%= render :partial => 'spree/blog_entries/blog_sidebar' %>
<% end %>

<h1><%= Spree.t(:blog_archive) %>: <%= t("date.month_names")[params[:month].to_i] unless params[:month].blank? %> <%= params[:year].to_i %></h1>
<%= render :partial => 'spree/blog_entries/blog_entries' %>

app/views/spree/blog_entries/author.html.erb
<% content_for :sidebar do %>
  <%= render :partial => 'spree/blog_entries/blog_sidebar' %>
<% end %>

<div class="row blog_author_info">
  <div class="col-md-6">
    <h1><%= "#{Spree.t :blog_author}: #{@author.nickname}" %></h1>
    <%= link_to @author.website_url, @author.website_url unless @author.website_url.blank? %>
  </div>
  <div class="col-md-6">
    <%= @author.bio_info %>
  </div>
</div>

<%= render :partial => 'spree/blog_entries/blog_entries' %>

app/views/spree/blog_entries/category.html.erb
<% content_for :sidebar do %>
  <%= render :partial => 'spree/blog_entries/blog_sidebar' %>
<% end %>

<h1><%= Spree.t(:blog_category) %>: <%= @category_name %></h1>
<%= render :partial => 'spree/blog_entries/blog_entries' %>

app/views/spree/blog_entries/show.html.erb
<% content_for :head do %>
  <% if !@blog_entry.author.blank? and !@blog_entry.author.google_plus_url.blank? %>
    <link rel="author" href="<%= @blog_entry.author.google_plus_url %>"/>
  <% end %>
<% end %>

<% content_for :sidebar do %>
  <%= render :partial => 'spree/blog_entries/blog_sidebar' %>
<% end %>

<div id="blog_entry_container" class=''>
  <div id="blog_entry_entry" class=''>

    <h1><%= @blog_entry.title %></h1>

    <div class="blog_entry_body">
      <%== @blog_entry.body %>
    </div>

    <%= render :partial => 'spree/blog_entries/blog_entry_details', :locals => {:blog_entry => @blog_entry} %>
  </div>

  <%= render :partial => 'spree/blog_entries/comments', :locals => {:blog_entry => @blog_entry}  %>
</div>

app/views/spree/blog_entries/tag.html.erb
<% content_for :sidebar do %>
  <%= render :partial => 'spree/blog_entries/blog_sidebar' %>
<% end %>

<h1><%= Spree.t(:blog_tag) %>: <%= @tag_name %></h1>
<%= render :partial => 'spree/blog_entries/blog_entries' %>